name: Deploy to GitHub Pages

on:
  push:
    branches:
      - "*" # Trigger on pushes to all branches
  pull_request:
    branches:
      - "*" # Trigger on pushes to all branches
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "Setup Dart and Flutter"
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: "Build Flutter Web Project"
        run: |
          flutter build web --base-href=/${{ github.event.repository.name }}/

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-web-build
          path: build/web/

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: flutter-web-build
          path: build/web/

      - name: Setup Pages
        uses: actions/configure-pages@v6.0.0

      - name: Upload artifact to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./build/web/"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
